version: '3.8'

services:
  web:
    build:
      context: ./plastic-django
      dockerfile: Dockerfile
    command: /root/.local/bin/uv run --locked manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000