

POST http://127.0.0.1:8000/api/product_types/
Content-Type: application/json

{
    "name" : "Chair"
}


###
POST http://127.0.0.1:8000/api/product_types/
Content-Type: application/json

{
    "name" : "Table"
}
