

POST http://127.0.0.1:8000/api/product_types/
Content-Type: application/json

{
    "name" : "Chair"
}


###
POST http://127.0.0.1:8000/api/product_types/
Content-Type: application/json

{
    "name" : "Table"
}


### 
POST http://127.0.0.1:8000/api/product_serials/
Content-Type: application/json

{
    "product_type_id": 1,
    "name": "Plastic Chair T1",
    "description": "Plastic Chair T1"
}

###
POST http://127.0.0.1:8000/api/product/
Content-Type: application/json

{
    "serial_id": 4,
    "mixed": false,
    "mix_id": 1,
    "pictures_URL": ""
}